version: "3.8"

services:
  esp-dotnet:
    container_name: "esp-dotnet"
    build:
      context: ./src/c#/Namirial.Esp.Plugin.Dotnet
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  esp-php:
    container_name: "esp-php"
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    volumes:
      - './src/php/esp-plugin:/app'
  esp-javascript:
    container_name: "esp-javascript"
    build:
      context: ./src/javascript
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  esp-java:
    container_name: "esp-java"
    build:
      context: ./src/java/esp-plugin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
  esp-python:
    container_name: "esp-python"
    build:
      context: ./src/python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
