version: "3.8"

services:
  esp-dotnet:
    container_name: "esp-dotnet"
    build:
      context: ./src/c#/Namirial.Esp.Plugin.Dotnet
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  esp-javascript:
    container_name: "esp-javascript"
    build:
      context: ./src/javascript
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
